apiVersion: v1
kind: Pod
metadata:
  labels:
    app: giropops
    service: webserver
  name: giropops
spec:
  containers:
  - image: nginx 
    name: giropops
    volumeMounts:
    - mountPath: /giropops
      name: first-volume
    resources:
      requests:
        cpu: "0.3"
        memory: "64Mi"
      limits:
        cpu: "0.6"
        memory: "128Mi"
  - image: ubuntu
    name: ubuntu
    args:
    - sleep
    - "60"  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: first-volume
    emptyDir:
      sizeLimit: 256Mi
