apiVersion: v1
kind: Pod
metadata:
  labels:
    app: giropops
  name: giropops
spec:
  containers:
  - image: nginx
    name: giropops
    ports:
    - containerPort: 80
    resources: {}
  restartPolicy: Always
